/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Generator Kotlin Sample
 * OpenAPI Generator を用いた自動生成のサンプルコードです
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomersTorokuParam
 */
export interface CustomersTorokuParam {
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    secondName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    firstNameKana: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    secondNameKana: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    addressNo: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    tel: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersTorokuParam
     */
    roleType: string;
}

/**
 * Check if a given object implements the CustomersTorokuParam interface.
 */
export function instanceOfCustomersTorokuParam(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "secondName" in value;
    isInstance = isInstance && "firstNameKana" in value;
    isInstance = isInstance && "secondNameKana" in value;
    isInstance = isInstance && "addressNo" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "tel" in value;
    isInstance = isInstance && "roleType" in value;

    return isInstance;
}

export function CustomersTorokuParamFromJSON(json: any): CustomersTorokuParam {
    return CustomersTorokuParamFromJSONTyped(json, false);
}

export function CustomersTorokuParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersTorokuParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'secondName': json['secondName'],
        'firstNameKana': json['firstNameKana'],
        'secondNameKana': json['secondNameKana'],
        'addressNo': json['addressNo'],
        'address': json['address'],
        'tel': json['tel'],
        'roleType': json['roleType'],
    };
}

export function CustomersTorokuParamToJSON(value?: CustomersTorokuParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'firstName': value.firstName,
        'secondName': value.secondName,
        'firstNameKana': value.firstNameKana,
        'secondNameKana': value.secondNameKana,
        'addressNo': value.addressNo,
        'address': value.address,
        'tel': value.tel,
        'roleType': value.roleType,
    };
}

