/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Generator Kotlin Sample
 * OpenAPI Generator を用いた自動生成のサンプルコードです
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomerInfo } from './CustomerInfo';
import {
    CustomerInfoFromJSON,
    CustomerInfoFromJSONTyped,
    CustomerInfoToJSON,
} from './CustomerInfo';

/**
 * 
 * @export
 * @interface Customers
 */
export interface Customers {
    /**
     * 
     * @type {Array<CustomerInfo>}
     * @memberof Customers
     */
    customers: Array<CustomerInfo>;
}

/**
 * Check if a given object implements the Customers interface.
 */
export function instanceOfCustomers(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "customers" in value;

    return isInstance;
}

export function CustomersFromJSON(json: any): Customers {
    return CustomersFromJSONTyped(json, false);
}

export function CustomersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Customers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customers': ((json['customers'] as Array<any>).map(CustomerInfoFromJSON)),
    };
}

export function CustomersToJSON(value?: Customers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customers': ((value.customers as Array<any>).map(CustomerInfoToJSON)),
    };
}

