/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Generator Kotlin Sample
 * OpenAPI Generator を用いた自動生成のサンプルコードです
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUsers
 */
export interface LoginUsers {
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    email?: string;
}

/**
 * Check if a given object implements the LoginUsers interface.
 */
export function instanceOfLoginUsers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginUsersFromJSON(json: any): LoginUsers {
    return LoginUsersFromJSONTyped(json, false);
}

export function LoginUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUsers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function LoginUsersToJSON(value?: LoginUsers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'user': value.user,
        'email': value.email,
    };
}

