/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Generator Kotlin Sample
 * OpenAPI Generator を用いた自動生成のサンプルコードです
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUsers
 */
export interface LoginUsers {
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    userUji?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUsers
     */
    userMei?: string;
}

/**
 * Check if a given object implements the LoginUsers interface.
 */
export function instanceOfLoginUsers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginUsersFromJSON(json: any): LoginUsers {
    return LoginUsersFromJSONTyped(json, false);
}

export function LoginUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUsers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'userUji': !exists(json, 'userUji') ? undefined : json['userUji'],
        'userMei': !exists(json, 'userMei') ? undefined : json['userMei'],
    };
}

export function LoginUsersToJSON(value?: LoginUsers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'userUji': value.userUji,
        'userMei': value.userMei,
    };
}

